results_dir: sample
num_repeats: 5
data_id: [0, 4]
parameters:
  D: 4
  relu_width: 1296
  linear_width: [16, 1296]
  layers: 2
  epochs: 1
  learning_rate: 1e-3
  weight_decay: 0
  regularization_lambda: [0.1]
  regularization_method: [standard_wd, term2]
  block_architecture: False