results_dir: TEST/dask_test
num_repeats: 5
data_id: [0, 2, 4, 6]
parameters:
  D: 4
  relu_width: 1296
  linear_width: 1296
  layers: 2
  epochs: 50000
  learning_rate: 1e-3
  regularization_lambda: [1e-1, 1e-3, 1e-5]
  regularization_method: [standard_wd, term2, none]
  block_architecture: False
