results_dir: FIXED/w_v_low_rank_regularized_10_datasets
num_repeats: 5
data_id: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
parameters:
  D: 4
  relu_width: 1296
  linear_width: 16
  layers: 2
  epochs: 1
  learning_rate: 1e-3
  weight_decay: 0
  regularization_lambda: [1e-1, 1e-3, 1e-5, 1e-7]
  regularization_method: [standard_wd, term2, none]
  block_architecture: False